### ISSUE TITLE
multiline warnings containing links are difficult to click due to resizing

### ISSUE THREAD

**Issue by braingram** [asdf-format/sphinx-asdf#51]
The active resizing to allow for easier reading of asdf file contents limits interaction with links in warning block text.
https://github.com/asdf-format/sphinx-asdf/blob/da575fbf2c95b84717c90f9419ffc7e103e6c262/sphinx_asdf/static/custom.css#L7

Perhaps a hover would allow for both uses but would require testing.

**Comment by WilliamJamieson** [comment]
First, hover seems incompatible with how the directive generates the page. This necessitated the click to increase size fix. I also find hover changes to not work well on mobile devices.

I believe this issue is rooted in your comment here: https://github.com/asdf-format/asdf/pull/1337#issuecomment-1433731516. First note that sphinx structures things so that `admonition` is the parent of directives like `warning` and `note`, see https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#directives for details. This means that click to resize for `warning` directives can be overridden by specifically changing the settings for `warning`.

Indeed, this is exactly how `note` is not resized, see: https://github.com/asdf-format/sphinx-asdf/blob/da575fbf2c95b84717c90f9419ffc7e103e6c262/sphinx_asdf/static/custom.css#L11-L13 this can simply be extended to include `warning`.

As for the reason why it has to affect all `admonition` is because when you look at the directives that `sphinx` uses to write the parts of ASDF files, it does them in pure `admonition` directives. So I had to modify the CSS for that directly in order to make it work.

**Comment by WilliamJamieson** [comment]
Note these changes were first developed as part of asdf-format/asdf#1142

**Comment by braingram** [comment]
After looking at this a bit more my vote is for removal of custom.css unless there are other uses aside from the resizing.

The resizing also interferes with selecting content within blocks. As one example, for the `external_array.asdf` file here:
https://asdf.readthedocs.io/en/latest/asdf/features.html#array-references
selecting `/asdf` at the end of the following line is impossible:
```yaml
asdf_library: !core/software-1.0.0 {author: The ASDF Developers, homepage: 'http://github.com/asdf-format/asdf',
```

Removing custom.css allows for normal use of the scroll bars in the blocks.

The resizing also does not consistently work on mobile and touches sometimes result in scrolling and other times result in resizing that resets the scrolling.

**Comment by WilliamJamieson** [comment]
Then remove it.
